id: PBA055098
initial_creation_type: input
source_metadata:
  title: Śāntideva Series
  language: en
  description: 'Texts by and about the Indian master Śāntideva (zhi ba lha), renowned
    author of the Bodhicaryāvatāra:'
  volume:
    8abde251f3a840c9bbf6c8e69d1b20f4:
      title: 'The Brightly Shining Sun: A Step-by-Step Guide to Meditating on the
        Bodhicaryāvatāra'
      parent: Bodhicaryāvatāra
    428a649c4e7341b992d216e75f829cfc:
      title: 'Bodhicaryāvatāra—Chapter 1: The Benefits of Bodhicitta'
      parent: Bodhicaryāvatāra Root Text
    caaf87e503254df1808a9af0a19e758f:
      title: 'Bodhicaryāvatāra—Chapter 2: Confession of Negativity'
      parent: Bodhicaryāvatāra Root Text
    4bbfab31c5a34bce8df177e2ef679922:
      title: 'Bodhicaryāvatāra—Chapter 3: Fully Adopting Bodhicitta'
      parent: Bodhicaryāvatāra Root Text
    094ad36697b046759612d7b60cddb0e1:
      title: Prayer to Śāntideva and Dam, Tsang and Jam of Katok
      parent: Prayers
created_at: '2022-03-01T02:22:42.792227'
last_modified_at: '2022-03-01T02:22:42.792236'
